# Generated by Django 3.1.5 on 2021-01-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('town', models.CharField(max_length=255, verbose_name='Town')),
                ('department', models.CharField(max_length=255, verbose_name='Department')),
                ('locality', models.CharField(max_length=255, null=True, verbose_name='Locality')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('is_bander', models.BooleanField(default=False, verbose_name='Is bander')),
            ],
            options={
                'verbose_name': 'Observer',
                'verbose_name_plural': 'Observers',
            },
        ),
        migrations.CreateModel(
            name='Plover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banding_year', models.IntegerField(verbose_name='Banding year')),
                ('metal_ring', models.CharField(max_length=20, unique=True, verbose_name='Metal ring')),
                ('code', models.IntegerField(verbose_name='Code')),
                ('color', models.CharField(choices=[('R', 'Red'), ('P', 'Pink'), ('W', 'White'), ('Y', 'Yellow'), ('G', 'Green')], default=0, max_length=1, verbose_name='Color')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], default=2, max_length=20, verbose_name='Sex')),
                ('age', models.CharField(max_length=5, verbose_name='Age')),
                ('banding_date', models.DateField(blank=True, null=True, verbose_name='Banding date')),
                ('banding_time', models.TimeField(blank=True, null=True, verbose_name='Banding time')),
                ('bander', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plovers', to='website.observer', verbose_name='Bander')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plovers', to='website.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Kentish plover',
                'verbose_name_plural': 'Kentish plovers',
                'unique_together': {('metal_ring', 'code', 'color')},
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('supposed_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], default=2, max_length=20, verbose_name='Supposed Sex')),
                ('coordinate_x', models.FloatField(null=True, verbose_name='X coordinate')),
                ('coordinate_y', models.FloatField(null=True, verbose_name='Y coordinate')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='website.location', verbose_name='Location')),
                ('observer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='website.observer', verbose_name='Observer')),
                ('plover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='website.plover', verbose_name='Plover')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'ordering': ['-date'],
            },
        ),
    ]
