# Generated by Django 3.1.7 on 2021-03-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210307_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plover',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('P', 'Pink'), ('W', 'White'), ('Y', 'Yellow'), ('G', 'Green')], default=0, max_length=1, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], default=2, max_length=20, null=True, verbose_name='Sex'),
        ),
    ]
